src/AppBundle/Form/Statistic.php
<?php

namespace AppBundle\Form;

use AppBundle\Form\Type\StatisticType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class PlayersType
 * @package AppBundle\Form\Type
 */
class Statistic extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('home', new StatisticType())
            ->add('guest', new StatisticType())
        ;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'statistic';
    }

}

src/AppBundle/Resources/views/Admin/edit.html.twig
{#

This file is part of the Sonata package.

(c) Thomas Rabaix <thomas.rabaix@sonata-project.org>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}

{% extends 'SonataAdminBundle:CRUD:edit.html.twig' %}

{% block html_attributes %}
    {{ parent() }}
    class="no-js"
    ng-app="FG"
    ng-controller="maincontroller"
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('/angular/bower_components/angular/angular.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/angular/bower_components/angular-route/angular-route.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/angular/bower_components/angular-resource/angular-resource.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/angular/bower_components/angular-animate/angular-animate.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/angular/bower_components/angular-sanitize/angular-sanitize.js') }}" type="text/javascript"></script>
    
    {% if app.debug %}
        <script src="{{ asset('angular/scripts/prefix/app_dev.js') }}"></script>
    {% else %}
        <script src="{{ asset('angular/scripts/prefix/app.js') }}"></script>
    {% endif %}
    
    <script src="{{ asset('/bundles/app/js/app.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/bundles/app/js/controller/MainController.js') }}" type="text/javascript"></script>
    <script src="{{ asset('/bundles/app/js/factory/factory.js') }}" type="text/javascript"></script>

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}

src/AppBundle/Resources/views/Admin/editAd.html.twig
{# empty Twig template #}

{% extends 'SonataAdminBundle:CRUD:edit.html.twig' %}
{% block form %}
    {{parent()}}

    {% if object.adPhotoName %}
        <img width="200" src="{{ (object.getAdPhotoDownloadLink) }}">
    {% endif %}

{% endblock %}

src/AppBundle/Resources/views/Admin/edit_tinymce.html.twig
{# empty Twig template #}

{% extends 'SonataAdminBundle:CRUD:edit.html.twig' %}
{% block form %}

    {{parent()}}
    {{ tinymce_init({selector: "textarea" }) }}
    
    <script>
        $('textarea').attr('class', 'tinymce');
    </script>
{% endblock %}

src/AppBundle/Resources/views/Admin/list_number.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}

    {% set number = null %}

    {% set playerTeams = object.playerTeams %}
    {% for playerTeam in playerTeams %}
        {% if playerTeam.status == constant("AppBundle\\Entity\\PlayerTeam::PLAYER_TEAM_CURRENT") %}
            {% set number = playerTeam.number  %}
        {% endif %}
    {% endfor %}

    <div>
        <p>
            {% if number %}
                {{ number }}
            {% endif %}
        </p>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Admin/list_team.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}

    {% set team = null %}

    {% set playerTeams = object.playerTeams %}
    {% for playerTeam in playerTeams %}
        {% if playerTeam.status == constant("AppBundle\\Entity\\PlayerTeam::PLAYER_TEAM_CURRENT") %}
            {% set team = playerTeam.team  %}
        {% endif %}
    {% endfor %}

    <div>
        <p>
            {% if team and team.name is defined %}
                {{ team.name }}
            {% endif %}
        </p>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Admin/list_wire.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}
    <div>
        <p >
            {{ object.videoPlayWire|length > 12 ? object.videoPlayWire|slice(0, 12) ~ '...' : object.videoPlayWire  }}
        </p>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Admin/players_edit.html.twig
{% block players_widget %}

    {% if attr.teamType is not defined %}
        {% set attr = attr|merge({'teamType': 0}) %}
    {% endif %}

    {% if attr.teamID is not defined %}
        {% set attr = attr|merge({'teamID': 0}) %}
    {% endif %}

    <style>
        .players {
        }

        .players table {
            width: 50%;
            border-collapse: collapse;
        }

        .players table th {
            text-align: center;
            padding: 5px 0;
            background-color: #e4e4e4;
            border: solid 1px #ccc;
        }
        .players table th:first-child input{
            width: 10px;
        }

        .players table td {
            padding: 3px 5px;
            border: solid 1px #ccc;
        }

        .players table td.tdCheckName {
            text-align: center;
        }

        .players table td.tdNo {
            text-align: right;
        }

        .players table td .checkName {
            width: 100px;
        }
        .lineUp{
            position: inherit !important;
             opacity: 1 !important;
        }
        .iCheck-helper{
            position: relative !important;
        }

        .number-search{
            width: 100px !important;
        }
    </style>

    <div class="players" style="margin: 10px 0" ng-show="teamHomePlayers.length || teamGuestPlayers.length" ng-init="initialize({{ value }},{{ attr.teamType }},{{ attr.teamID }});">
        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Player Name</th>
                    <th>Line ups</th>
                    <th>Goal</th>
                    <th>Yellow card</th>
                    <th>Red card</th>
                    <th>Substitute</th>
                </tr>
                <tr>
                    {#<th></th>#}
                    {% if attr.teamType == 0 %}
                        <th><input class="number-search" ng-model="homeSearch.number" /></th>
                        <th><input ng-model="homeSearch.player.full_name" /></th>
                    {% endif %}
                    {% if attr.teamType == 1 %}
                        <th><input class="number-search" ng-model="guestSearch.number" /></th>
                        <th><input ng-model="guestSearch.player.full_name" /></th>
                    {% endif %}
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% if attr.teamType == 0 %}
                <tr ng-repeat="teamElement in teamHomePlayers |filter:homeSearch " ng-init="teamId = teamHome">
                    {% endif %}
                    {% if attr.teamType == 1 %}
                <tr ng-repeat="teamElement in teamGuestPlayers |filter:guestSearch" ng-init="teamId = teamGuest">
                    {% endif %}
                    {% verbatim %}
                        <td class="tdNo">{{ teamElement.number}}</td>
                        <td data-ng-init="teamElement.player.full_name = teamElement.player.first_name+teamElement.player.last_name">{{ teamElement.player.full_name }}</td>
                        <td style="text-align: center">
                            <input class="lineUp" type="checkbox" name="events[{{ teamId }}][{{ teamElement.player.id }}][lineUps]" value="1" ng-model="teamElement.lineup">
                        </td>

                        <td class="tdCheckName">
                            <input type="text" name="events[{{ teamId }}][{{ teamElement.player.id }}][goal]" value="" ng-model="teamElement.goal" class="checkName" min="0" max="200">
                        </td>
                        <td class="tdCheckName">
                            <input type="text" name="events[{{ teamId }}][{{ teamElement.player.id }}][yCard]" value="" ng-model="teamElement.yellow" class="checkName" min="0" max="200">
                        </td>
                        <td class="tdCheckName">
                            <input type="text" name="events[{{ teamId }}][{{ teamElement.player.id }}][rCard]" value="" ng-model="teamElement.red" class="checkName" min="0" max="200">
                        </td>
                        <td class="tdCheckName">
                            <input type="text" name="events[{{ teamId }}][{{ teamElement.player.id }}][substitude]" value="" ng-model="teamElement.subs" class="checkName" min="0" max="200">
                        </td>
                    {% endverbatim %}
                </tr>
            </tbody>


        </table>
    </div>



{% endblock %}

src/AppBundle/Resources/views/Admin/statistic_type.html.twig
{% block statistic_widget %}

    {% set oneWidget = form['home'] %}

    <style>
        .statistic-title {
            width: 150px ;
            text-align: center;
        }

        .field-td{
            margin-bottom: 10px;
            height: 40px;

        }

    </style>

    <table>
        <thead>
            <tr>
                <th style="text-align: center">Home Team</th>
                <th class="statistic-title"> </th>
                <th style="text-align: center">Guest Team</th>
            </tr>
        </thead>

        <tbody>
        {% for key, widget in oneWidget %}
            <tr>
                <td class="field-td">{{ form_widget(form['home'][key]) }}</td>
                <td class="statistic-title">{{ widget.vars.label }}</td>
                <td class="field-td">{{ form_widget(form['guest'][key]) }}</td>
            </tr>
        {% endfor %}

        </tbody>


    </table>

{% endblock %}